# 서울시 자치구 년도별 CCTV 설치 현황 데이터 구하기

출처
- 서울 열린데이터 광장 (data.seoul.go.kr)

내용
- 서울시 주민등록 인구 (동별) 통계
- 서울시 자치구 년도별 CCTV 설치 현황 

# 데이터 파일 불러오기

In [113]:
import pandas as pd

## csv파일 안에 한글이 포함되어있다면 인코딩 => UTF-8

In [114]:
# 데이터 출처 : 서울 열린데이터 광장 (data.seoul.go.kr)
cctv_seoul = pd.read_csv('./data/cctv_in_seoul.csv', encoding='utf-8')

## head() - pandas 데이터의 첫 5행

In [115]:
cctv_seoul.head()

기관명       소계 2011년 이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년
0  강 남 구   5,221    1,944   195.0  316.0   430   546.0  765.0  577.0  448.0
1  강 동 구   1,879      303   387.0  134.0    59   144.0  194.0  273.0  385.0
2  강 북 구   1,265      243    88.0  141.0    74   145.0  254.0    1.0  319.0
3  강 서 구   1,617      219   155.0  118.0   230   187.0  190.0  264.0  254.0
4  관 악 구   3,985      430    56.0  419.0   487   609.0  619.0  694.0  671.0

In [116]:
cctv_seoul.columns

Index(['기관명', '소계', '2011년 이전', '2012년', '2013년', '2014년', '2015년', '2016년',
       '2017년', '2018년'],
      dtype='object')

In [117]:
cctv_seoul.columns[0]

'기관명'

In [118]:
cctv_seoul.columns[0:3]

Index(['기관명', '소계', '2011년 이전'], dtype='object')

In [119]:
cctv_seoul.columns[-1]

'2018년'

In [120]:
cctv_seoul.columns[:]

Index(['기관명', '소계', '2011년 이전', '2012년', '2013년', '2014년', '2015년', '2016년',
       '2017년', '2018년'],
      dtype='object')

## 칼럼 / 인덱스 이름 바꾸기

칼럼 이름 바꾸기

: df.columns = ['a', 'b']

: df.rename(columns = {'old_nm' : 'new_nm'), inplace = True)


인덱스 이름 바꾸기

: df.index = ['a', 'b']

: df.rename(index = {'old_nm': 'new_nm'), inplace = True)

inplace=True는 데이터 변수의 내용을 갱신하라는 의미

In [121]:
cctv_seoul.rename(columns={'기관명':'구별'}, inplace=True)
cctv_seoul.head()

구별       소계 2011년 이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년
0  강 남 구   5,221    1,944   195.0  316.0   430   546.0  765.0  577.0  448.0
1  강 동 구   1,879      303   387.0  134.0    59   144.0  194.0  273.0  385.0
2  강 북 구   1,265      243    88.0  141.0    74   145.0  254.0    1.0  319.0
3  강 서 구   1,617      219   155.0  118.0   230   187.0  190.0  264.0  254.0
4  관 악 구   3,985      430    56.0  419.0   487   609.0  619.0  694.0  671.0

In [122]:
cctv_seoul.rename(columns={cctv_seoul.columns[0]:'구별'}, inplace=True)
cctv_seoul.head()

구별       소계 2011년 이전  2012년  2013년  2014년  2015년  2016년  2017년  2018년
0  강 남 구   5,221    1,944   195.0  316.0   430   546.0  765.0  577.0  448.0
1  강 동 구   1,879      303   387.0  134.0    59   144.0  194.0  273.0  385.0
2  강 북 구   1,265      243    88.0  141.0    74   145.0  254.0    1.0  319.0
3  강 서 구   1,617      219   155.0  118.0   230   187.0  190.0  264.0  254.0
4  관 악 구   3,985      430    56.0  419.0   487   609.0  619.0  694.0  671.0

## 엑셀 파일 불러오기

In [126]:
pop_seoul = pd.read_excel('./data/population_in_seoul.xlsx', encoding='utf-8')
pop_seoul.head()

기간  자치구       세대        인구     인구.1     인구.2     인구.3     인구.4  \
0        기간  자치구       세대        합계       합계       합계      한국인      한국인   
1        기간  자치구       세대         계       남자       여자        계       남자   
2  2019.1/4   합계  4290922  10054979  4909387  5145592  9770216  4772134   
3  2019.1/4  종로구    73914    162913    78963    83950   152778    74536   
4  2019.1/4   중구    61800    135836    66720    69116   125942    61992   

      인구.5    인구.6    인구.7    인구.8  세대당인구  65세이상고령자  
0      한국인   등록외국인   등록외국인   등록외국인  세대당인구  65세이상고령자  
1       여자       계      남자      여자  세대당인구  65세이상고령자  
2  4998082  284763  137253  147510   2.28   1436125  
3    78242   10135    4427    5708   2.07     26981  
4    63950    9894    4728    5166   2.04     22421

In [128]:
pop_seoul = pd.read_excel('./data/population_in_seoul.xlsx', 
                          header = 2,
                          # 자치구, 인구(전체), 인구(한국인), 인구(외국인), 인구(65세이상고령자)
                          parse_cols = 'B, D, G, J, N', 
                          encoding='utf-8')
pop_seoul.head()

자치구         계      계.1     계.2  65세이상고령자
0   합계  10054979  9770216  284763   1436125
1  종로구    162913   152778   10135     26981
2   중구    135836   125942    9894     22421
3  용산구    245139   229168   15971     38049
4  성동구    314608   306404    8204     43076

In [133]:
pop_seoul.rename(columns={pop_seoul.columns[0] : '구별',
                          pop_seoul.columns[1] : '인구수',
                          pop_seoul.columns[2] : '한국인',
                          pop_seoul.columns[3] : '외국인',
                          pop_seoul.columns[4] : '고령자'},
                          inplace = True
                )
pop_seoul.head()

구별       인구수      한국인     외국인      고령자
0   합계  10054979  9770216  284763  1436125
1  종로구    162913   152778   10135    26981
2   중구    135836   125942    9894    22421
3  용산구    245139   229168   15971    38049
4  성동구    314608   306404    8204    43076

# pandas 기초

In [134]:
import pandas as pd
import numpy as np

## Series : pandas의 데이터 유형 중 기초

In [137]:
s = pd.Series([1, 3, 5, np.nan, 6, 8]) # NaN(Not A Number)
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [138]:
s = pd.Series([10, 20, 30, 40, 50, 100])
s

0     10
1     20
2     30
3     40
4     50
5    100
dtype: int64

## date_range : 날짜형 데이터

In [139]:
date = pd.date_range('20200229', periods=6)
date

DatetimeIndex(['2020-02-29', '2020-03-01', '2020-03-02', '2020-03-03',
               '2020-03-04', '2020-03-05'],
              dtype='datetime64[ns]', freq='D')

## DataFrame
rand: 0부터 1사이의 균일 분포

randn: 가우시안 표준 정규 분포

randint: 균일 분포의 정수 난수

In [160]:
df = pd.DataFrame(np.random.rand(6,4),
                  index=date,
                  columns=['A','B','C','D']
                 )
df

A         B         C         D
2020-02-29  0.059984  0.979528  0.507194  0.203106
2020-03-01  0.786502  0.267390  0.037620  0.730194
2020-03-02  0.990480  0.170513  0.612750  0.143789
2020-03-03  0.058572  0.112087  0.150764  0.960280
2020-03-04  0.813051  0.033108  0.519018  0.842534
2020-03-05  0.846291  0.175919  0.967206  0.656989

In [161]:
np.random.randint(10,20, size=4)

array([18, 11, 19, 11])

In [162]:
np.random.randint(10,20, size=7)

array([12, 19, 16, 11, 11, 17, 12])

In [163]:
df = pd.DataFrame(np.random.randn(6,4),
                  index=date,
                  columns=['A','B','C','D']
                 )
df

A         B         C         D
2020-02-29  0.278032 -0.268001  0.248610  0.242158
2020-03-01  0.698163 -0.375038  0.490262 -0.833122
2020-03-02  0.425479 -1.027298  0.108145  0.624383
2020-03-03 -0.057369 -1.555127 -0.258901 -2.024712
2020-03-04  0.581556 -1.484529 -3.510661  0.094493
2020-03-05 -1.905795 -0.440441  0.294173 -0.273018

### head()

In [164]:
df.head(3)

A         B         C         D
2020-02-29  0.278032 -0.268001  0.248610  0.242158
2020-03-01  0.698163 -0.375038  0.490262 -0.833122
2020-03-02  0.425479 -1.027298  0.108145  0.624383

### info()

In [168]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6 entries, 2020-02-29 to 2020-03-05
Freq: D
Data columns (total 4 columns):
A    6 non-null float64
B    6 non-null float64
C    6 non-null float64
D    6 non-null float64
dtypes: float64(4)
memory usage: 240.0 bytes


### index

In [165]:
df.index

DatetimeIndex(['2020-02-29', '2020-03-01', '2020-03-02', '2020-03-03',
               '2020-03-04', '2020-03-05'],
              dtype='datetime64[ns]', freq='D')

### columns

In [166]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

### values

In [167]:
df.values

array([[ 0.27803208, -0.26800131,  0.24861026,  0.2421585 ],
       [ 0.69816347, -0.37503768,  0.49026179, -0.83312204],
       [ 0.42547921, -1.02729795,  0.10814514,  0.62438329],
       [-0.05736925, -1.55512661, -0.25890088, -2.02471191],
       [ 0.5815557 , -1.48452927, -3.51066106,  0.09449316],
       [-1.90579501, -0.44044149,  0.29417299, -0.27301796]])

### describe()
* 통계적 개요
* 

In [169]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.003344 -0.858406 -0.438062 -0.361636
std    0.971520  0.576696  1.525829  0.952977
min   -1.905795 -1.555127 -3.510661 -2.024712
25%    0.026481 -1.370221 -0.167139 -0.693096
50%    0.351756 -0.733870  0.178378 -0.089262
75%    0.542537 -0.391389  0.282782  0.205242
max    0.698163 -0.268001  0.490262  0.624383

In [170]:
df

A         B         C         D
2020-02-29  0.278032 -0.268001  0.248610  0.242158
2020-03-01  0.698163 -0.375038  0.490262 -0.833122
2020-03-02  0.425479 -1.027298  0.108145  0.624383
2020-03-03 -0.057369 -1.555127 -0.258901 -2.024712
2020-03-04  0.581556 -1.484529 -3.510661  0.094493
2020-03-05 -1.905795 -0.440441  0.294173 -0.273018

## 열 1개 선택하기

In [14]:
cctv_seoul.기관명

0       강 남 구
1       강 동 구
2       강 북 구
3       강 서 구
4       관 악 구
5       광 진 구
6       구 로 구
7       금 천 구
8       노 원 구
9       도 봉 구
10       동대문구
11      동 작 구
12      마 포 구
13       서대문구
14      서 초 구
15      성 동 구
16      성 북 구
17      송 파 구
18      양 천 구
19       영등포구
20      용 산 구
21      은 평 구
22      종 로 구
23    중     구
24      중 랑 구
25        NaN
26        NaN
27        NaN
Name: 기관명, dtype: object

In [15]:
cctv_seoul['기관명']

0       강 남 구
1       강 동 구
2       강 북 구
3       강 서 구
4       관 악 구
5       광 진 구
6       구 로 구
7       금 천 구
8       노 원 구
9       도 봉 구
10       동대문구
11      동 작 구
12      마 포 구
13       서대문구
14      서 초 구
15      성 동 구
16      성 북 구
17      송 파 구
18      양 천 구
19       영등포구
20      용 산 구
21      은 평 구
22      종 로 구
23    중     구
24      중 랑 구
25        NaN
26        NaN
27        NaN
Name: 기관명, dtype: object

## 열 여러개 선택하기

In [16]:
cctv_seoul[['기관명','2014년','2018년']]

기관명    2014년  2018년
0     강 남 구     430   448.0
1     강 동 구      59   385.0
2     강 북 구      74   319.0
3     강 서 구     230   254.0
4     관 악 구     487   671.0
5     광 진 구      87   346.0
6     구 로 구     187   486.0
7     금 천 구     101   530.0
8     노 원 구      80   156.0
9     도 봉 구     185    71.0
10     동대문구   1,326   197.0
11    동 작 구     503   255.0
12    마 포 구      70   195.0
13     서대문구     114   194.0
14    서 초 구     134   396.0
15    성 동 구     101   294.0
16    성 북 구     241   643.0
17    송 파 구      21   396.0
18    양 천 구     169   830.0
19     영등포구     217   793.0
20    용 산 구     107    73.0
21    은 평 구     343   367.0
22    종 로 구     132   101.0
23  중     구      80   328.0
24    중 랑 구     770     9.0
25      NaN      NaN    NaN
26      NaN      NaN    NaN
27      NaN      NaN    NaN

## 데이터를 직접 만들어 봄

In [40]:
sample_data = {'기관명':['강남구','강동구','강북구'], '2014년':[430, 59, 74], '2018년':[448.0, 385.0, 319.0]}

In [41]:
df = pd.DataFrame(sample_data)

In [42]:
df

2014년  2018년  기관명
0    430  448.0  강남구
1     59  385.0  강동구
2     74  319.0  강북구

### index의 순서를 바꿈

In [54]:
df = pd.DataFrame(sample_data, columns=['기관명','2014년','2018년'])
df

기관명  2014년  2018년
0  강남구    430  448.0
1  강동구     59  385.0
2  강북구     74  319.0

In [52]:
df = df.reindex(index=[0,2,1])
df

기관명  2014년  2018년
0  강남구  430.0  448.0
2  강북구   74.0  319.0
1  강동구   59.0  385.0

In [59]:
import numpy as np

In [60]:
df['합계'] = np.nan
df

기관명  2014년  2018년  합계
0  강남구    430  448.0 NaN
1  강동구     59  385.0 NaN
2  강북구     74  319.0 NaN

In [61]:
df['합계'] = df['2014년'] + df['2018년']
df

기관명  2014년  2018년     합계
0  강남구    430  448.0  878.0
1  강동구     59  385.0  444.0
2  강북구     74  319.0  393.0

In [62]:
df.loc[3] = np.nan

In [64]:
df

기관명  2014년  2018년     합계
0  강남구  430.0  448.0  878.0
1  강동구   59.0  385.0  444.0
2  강북구   74.0  319.0  393.0
3  NaN    NaN    NaN    NaN

In [66]:
df.loc[4] = ['강서구','230','254',np.nan]
df

기관명 2014년 2018년     합계
0  강남구   430   448  878.0
1  강동구    59   385  444.0
2  강북구    74   319  393.0
3  NaN   NaN   NaN    NaN
4  강서구   230   254    NaN

In [69]:
df.loc[5] = df.loc[0]
df

기관명 2014년 2018년     합계
0  강남구   430   448  878.0
1  강동구    59   385  444.0
2  강북구    74   319  393.0
3  NaN   NaN   NaN    NaN
4  강서구   230   254    NaN
5  강남구   430   448  878.0